### ISSUE TITLE
Bug with the last element in the list

### ISSUE THREAD

**Issue by gmarceaucaron** [mirkobronzi/mask_ipynb#1]
```
"source": [
"\n",
 "**Possible answers**:\n",
"1.   A simple measure of performance is the accuracy, the number of good predictions over the total number of examples.\n",
"2.   This model has an accuracy of 4/5 = 80%.\n",
"\n",]
```
The script inserts a comma after every element in the list even the last one, which produces a JSON error in Colab.

**Comment by mirkobronzi** [comment]
Hi @gmarceaucaron , I tried and I am not sure I can reproduce the error.
I added an example in the code (see the folder example).
Can you modify it to reproduce the error? (you can commit it on a separate branch)

I will fix it then..
Thanks!

**Comment by gmarceaucaron** [comment]
You can run the script on the MLP tutorial and upload it to Colab, there will be a character number associated to the first error that you can navigate to with vim. In the MLP tutorial, the errors occur 3 times.
